#+TITLE: solaR: Solar Radiation and Photovoltaic Systems with R
#+DESCRIPTION: solaR
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+HTML_HEAD:    <link rel="stylesheet" type="text/css" href="styles.css" />
#+OPTIONS:   num:nil toc:nil ^:nil

* Introduction

The =solaR= package allows for reproducible research both for
photovoltaics (PV) systems performance and solar radiation. It
includes a set of classes, methods and functions to calculate the
sun geometry and the solar radiation incident on a photovoltaic
generator and to simulate the performance of several applications
of the photovoltaic energy. This package performs the whole
calculation procedure from both daily and intradaily global
horizontal irradiation to the final productivity of grid-connected
PV systems and water pumping PV systems.

It is designed using a set of S4 classes whose core is a group of
slots with multivariate time series. The classes share a variety
of methods to access the information and several visualization
methods. In addition, the package provides a tool for the visual
statistical analysis of the performance of a large PV plant
composed of several systems.

Although =solaR= is primarily designed for time series associated to
a location defined by its latitude/longitude values and the
temperature and irradiation conditions, it can be easily combined
with spatial packages for space-time analysis.  

* Software

The stable version of =solaR= is hosted at [[https://cran.r-project.org/package=solaR][CRAN]]. 
The development version is available at [[https://github.com/oscarperpinan/solar/][GitHub]].

* Documentation

The best place to learn how to use the package is the companion [[https://doi.org/10.18637/jss.v050.i09][paper]]
published by the Journal of Statistical Software. [[https://oscarperpinan.github.io/esf/][This book]] (in
Spanish) contains detailed information about solar radiation and
photovoltaic systems. In [[https://oscarperpinany.github.io/][my articles]] I frequently use =solaR=.

* Citation 

If you use =solaR=, please cite it in any publication reporting
results obtained with this software:

#+begin_src verbatim
Perpiñán Lamigueiro, O. (2012).
solaR: Solar Radiation and Photovoltaic Systems with R.
Journal of Statistical Software, 50(9), 1–32.
https://doi.org/10.18637/jss.v050.i09
#+end_src

A BibTeX entry for LaTeX users is
#+begin_src verbatim
  @Article{,
    title = {{solaR}: Solar Radiation and Photovoltaic Systems with {R}},
    author = {Oscar Perpi{\~n}{\'a}n},
    journal = {Journal of Statistical Software},
    year = {2012},
    volume = {50},
    number = {9},
    pages = {1--32},
    doi = {10.18637/jss.v050.i09}
  }
#+end_src

* References

  =solaR= has been cited in [[https://scholar.google.com/scholar?oi=bibs&hl=es&cites=3271105799150114365][several papers]].
  
  -----
